version: '2.3'
services:
    ch-nginx:
        build:
            context: ./
            dockerfile: ./docker/ch-nginx/Dockerfile
        image: ch-nginx:latest
        container_name: ch-nginx
        volumes:
            - .:/src
        ports:
            - 80:80
            - 443:443
        depends_on:
            - ch-php-fpm
    ch-php-fpm:
        build:
            context: ./
            dockerfile: ./docker/ch-php-fpm/Dockerfile
        image: ch-php-fpm:latest
        container_name: ch-php-fpm
        volumes:
            - .:/src
    ch-php-cli:
        build:
            context: ./
            dockerfile: ./docker/ch-php-cli/Dockerfile
        image: ch-php-cli:latest
        container_name: ch-php-cli
        tty: true
        stdin_open: true
        volumes:
            - .:/src
            - ./docker/ch-php-cli/log:/etc/supervisor/log
    ch-mariadb:
        image: mariadb:10.3.11
        container_name: ch-mariadb
        ports:
            - 3306:3306
        volumes:
            - ch-mariadata:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=123456
    ch-phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.8.3
        container_name: ch-phpmyadmin
        environment:
            - PMA_HOST=ch-mariadb
        ports:
            - 8080:80
    ch-elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
        container_name: ch-elasticsearch
        volumes:
            - ch-elasticsearchdata:/usr/share/elasticsearch/data
        environment:
            - node.name=stats-elasticsearch-node-01
            - cluster.name=stats-elasticsearch-cluster-01
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
    ch-kibana:
        image: docker.elastic.co/kibana/kibana:7.6.0
        container_name: ch-kibana
        environment:
            - ELASTICSEARCH_HOSTS=http://ch-elasticsearch:9200
        ports:
          - 5601:5601
    ch-rabbitmq:
        build:
            context: ./
            dockerfile: ./docker/ch-rabbitmq/Dockerfile
        image: ch-rabbitmq:latest
        container_name: ch-rabbitmq
        hostname: host_ch
        sysctls:
            - net.core.somaxconn=1024
        tty: true
        volumes:
            - ch-rabbitmqdata:/var/lib/rabbitmq
        ports:
            - 15672:15672
    ch-redis:
        image: redis:5.0.7
        container_name: ch-redis
        volumes:
            - ch-redis-data:/data
        ports:
          - 6379:6379
volumes:
    ch-mariadata:
    ch-elasticsearchdata:
    ch-redis-data:
    ch-rabbitmqdata:
      driver: local

